### ISSUE TITLE
[Bug]: Exponential Graph not displaying line

### ISSUE THREAD

**Issue by Beta-Computer** [leonhma/obsidian-functionplot#3]
### What happened?

when using the following configuration the graph doesn't show the line.
when I hover over the graph it does show the coordinates.

### Additional info

```functionplot
---
title: log Graph
disableZoom: true
bounds: [-4, 4, -4, 4]
grid: false
xLabel: x
yLabel: y
---
f(x) = 2^x
```
<img width="649" alt="image" src="https://user-images.githubusercontent.com/67995456/173223015-fe52ca65-1b6f-4dac-8c19-407aa89e750f.png">

**Comment by leonhma** [comment]
What I found after just testing this is that apparently the library that renders the html for the graph doesn't like `x` in the exponent?
I will open an issue there, but as this is not really under my control it could take some time.

**Comment by leonhma** [comment]
Fixed with `1.0.2`

It was a bit quick of me to blame the library I am using for this issue. Turns out they are using interval arithmetic and exponential functions are a known issue. Setting the graph type as a polyline solved this problem. So I did that.

Sorry for the delay as I was on vacation for the last two weeks.

**Comment by Beta-Computer** [comment]
I found another way to fix it using `f(x) = exp(x)`

**Comment by leonhma** [comment]
Can you verify you are on version `1.0.2` for me? I don't have this issue
and it should be fixed with the latest release.
