### ISSUE TITLE
Square wave amplitude line not visible

### ISSUE THREAD

**Issue by KrazyManJ** [leonhma/obsidian-functionplot#82]
### What happened?

I've tried to make square digital-like signal wave with this function (official function from [Wikipedia](https://en.wikipedia.org/wiki/Square_wave)):

```
f(x)= sign(sin(2*PI*x))
```

But it only contains upper and lower straight lines instead of connecting them and make square wave

![image](https://user-images.githubusercontent.com/79614430/208394913-c2511efa-9dfb-45bd-a50a-be135007dd27.png)

I hope that i described it well.

### Please confirm

- [X] I have checked that I am using the latest version of the plugin released.
- [X] I have searched for similar issues, but found none.

**Comment by leonhma** [comment]
I can't test it currently, but I suspect this I'd due to how the plots are made. The plotter samples the function at many points and then draws these points. Now, the sign function never outputs a value between -1 and 1, and so there is no line connecting the two values. I am planning on allowing more configuration options for the function, so that you can make this a function without jump discontinuities.

**Comment by KrazyManJ** [comment]
@leonhma Yea, that sounds like a good idea how to improve it. I hope you will add it as soon as possible, thank you for your quick reply!
